# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: publish
      run: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: published-app
        path: ${{ github.workspace }}/bin/Release/netcoreapp3.1/publish
